
# Development overrides for docker-compose.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: celery -A app.celery_app worker --loglevel=debug --concurrency=2

  # Add a development database browser
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db